### ISSUE TITLE
Can you add backtest functionality?

### ISSUE THREAD

**Issue by gselsidi** [Timonsc/HAApy#2]
Hi would be cool if you could add backtest functionality to test different combination, leverage, and get general performance data. 

Thanks

**Comment by Timonsc** [comment]
What combinations are you interested in? This is an implementation of Hybrid Asset Allocation as described in the paper and not meant as a general tool for backtesting strategies. There is many online resources where you can do this. 

Most of the performance data of this strategy is provided by Keller and Keuning in the paper and on their websites. For example [here](https://indexswingtrader.blogspot.com/2023/02/introducing-hybrid-asset-allocation-haa.html). You might be interested in the comment section of that blog where many suggestions are done to improve the strategy but often proved to perform worse than the original. 

Another issue with backtesting is finding accurate data that goes back far enough to be able to draw definitive conclusions from. This is especially an issue for testing with the leveraged ETFs as they are relatively new. 

If you'd like to see changes to the code, I need you to be more specific about your suggestions. Also, I'm open to PRs if we've agreed on the the to be added functionality.

Kr,
Timon

**Comment by gselsidi** [comment]
Yeah makes sense, probably easier to do it in quantconnect.

Think someone started on it but they couldn’t get the performance to match

https://www.quantconnect.com/forum/discussion/14842/hybrid-asset-allocation/
